using System;
using System.Collections.Generic;
using SmartaHemmet.Appliances;
using SmartaHemmet.Controllers;
SmartHomeController controller = new SmartHomeController();
controller.AddDevice(new Washer("Cylinda","Bathroom",18));
controller.AddDevice(new Refrigerator("Electrolux","Kitchen",2));
controller.AddDevice(new Oven("Elon","Kitchen",300));
controller.AddDevice(new RobotVaccum("Tesla","Bedroom",0.67f));
controller.AddDevice(new CoffeeMachine("Nespresso","Living room",2));
controller.AddDevice(new GamingConsole("Xbox", "Living room"));
controller.PrintStatusReport();
Console.WriteLine();
controller.TurnOnAll();
Console.WriteLine();
double totalEnergy = controller.GetTotalDailyEnergyUsage();
Console.WriteLine($"Total daily energy usage: {totalEnergy} kWh");
Console.WriteLine();
controller.ScheduleAllSchedulableDevices(DateTime.Now.AddHours(2));
Console.WriteLine();
controller.TurnOffAll();